### PR TITLE
Add default support for the Propshaft asset pipeline

### PR DESCRIPTION
**Pull request by rmacklin**
Follow-up to #60

Closes https://github.com/rails/importmap-rails/issues/42

New rails 7 applications can be generated with Propshaft as an alternative asset pipeline to Sprockets: https://github.com/rails/rails/pull/43261. Per https://github.com/rails/importmap-rails/issues/42#issuecomment-929321343, we want importmap-rails to work out of the box with either of those asset pipeline options, so we'll automatically add `Propshaft::MissingAssetError` to the `rescuable_asset_errors` if `Propshaft` is detected. This allows the test suite to pass when run against an application that uses Propshaft instead of Sprockets. To that end, we've extended the CI matrix to also run our test suite continuously against a rails 7 application that uses Propshaft.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Can you rebase and make it ready to review?

**Comment by rmacklin** [comment]
Okay, I rebased the branch, but I still haven't addressed the test coverage issue. I did notice we have this:
https://github.com/rails/importmap-rails/blob/a711ebbda5f803f4b4decc00fa6cd71f6e9395f8/Gemfile#L7-L8
although it doesn't currently appear to be used - we aren't using the CI matrix to test against different rails versions. Perhaps I should start by adding that, and then I can follow up here by adding a conditional in the Gemfile that swaps out sprockets-rails for propshaft and then extend the CI matrix to exercise that as well.

**Comment by rmacklin** [comment]
@rafaelfranca I've opened https://github.com/rails/importmap-rails/pull/73 to expand the CI matrix to test against multiple versions of rails. If that looks good, I'll update this PR accordingly and then mark it ready for review.

**Comment by rmacklin** [comment]
@rafaelfranca Done!

**Pull request merged**
