### PR TITLE
Upgraded es-module-shims to v1.5.5

### PR DESCRIPTION
**Pull request by iainbeeston**
The current version of es-module-shims provided
by importmap-rails (v1.4.6) requires allowing
`frame-src: blob:` in an app's CSP policy (it
creates an iframe with a blob as it's source
in order to perform feature detection). This is
quite a permissive thing to allow in csp and
I wouldn't recommend it if there is an alternative.

Since v1.4.7 es-module-shims no longer uses a
blob and it will work with `script-src: 'self'`
instead. I've upgraded to the latest version,
which is v1.5.5. For more details about the
CSP issue and it's fix see:

* https://github.com/guybedford/es-module-shims/pull/265
* https://github.com/guybedford/es-module-shims/pull/290

### CODE REVIEW

**Comment by iainbeeston** [comment]
I've assumed that a minor version upgrade won't be a problem as this is a shim and isn't directly called by the gem (AFAIK)

**Comment by dhh** [comment]
Cc @guybedford ring any bells?

**Comment by crohr** [comment]
@guybedford Thanks for the follow-up, I'll attempt to use ES Module Shims 1.5.4 and report if that works.

**Comment by guybedford** [comment]
@crohr thanks for bisecting further here - it does sound like it is likely that one line diff in `src/features.js` then. I've posted a fix in https://github.com/guybedford/es-module-shims/pull/298 since it is actually ok to revert that now for other reasons. If you're able to verify that diff before we land that would be a great help.

**Comment by guybedford** [comment]
I've published a 1.5.6 that should solve this issue if the bisection was correct!

**Comment by crohr** [comment]
@guybedford I can confirm that v1.5.6 works in React Native Webview on iOS. Thanks a lot!

**Pull request merged**
