### PR TITLE
Drop the bundled shim

### PR DESCRIPTION
**Pull request by dhh**
It's no longer needed with full support for import maps in all modern browsers.

### CODE REVIEW

**Comment by jonathandean** [comment]
Warning that this breaks JS on all browsers on iOS 16 and below, even if you download the latest version available for that OS. Verified on Safari, Chrome, and Duck Duck Go on a fresh install. This was a significant portion of my e-commerce site's users (12%+). I understand that these aren't "modern" browsers but this feels fairly premature for a lot of sites out there - so update with care.

**Comment by dhh** [comment]
That's why this is a major version bump. You can continue using 1.x for shim compatibility.

**Comment by jonathandean** [comment]
Sure, but being stuck on 1.x for an unknown amount of time isn't ideal. You'll be picking between new features in the 2.x release line and a fair amount of site traffic for most websites. Feels a bit idealistic in my opinion.

At any rate, it works to add the import manually ahead of the call to `javascript_importmap_tags` to be able to keep the 2.x version:

```html
<script async src="https://ga.jspm.io/npm:es-module-shims@1.8.2/dist/es-module-shims.js" data-turbo-track="reload"></script>

<%= javascript_importmap_tags %>
```

**Comment by wakairo** [comment]
[The Rails Guides refers to Es-module-shims](https://github.com/rails/rails/blob/main/guides/source/asset_pipeline.md#usage), but the latest version (2.x) does not insert the shims, which can be misleading. \
Should the reference to the shims be removed from the Rails Guides?

**Comment by wakairo** [comment]
Before updating the Rails Guides, first, I have sent PR #249 that add how to support legacy browsers with Es-module-shims to the README.

**Comment by wakairo** [comment]
I have submitted [the PR on the Rails](https://github.com/rails/rails/pull/51369) to update the Guides to reflect this PR #216.

**Pull request merged**
