### PR TITLE
Use the application file_watcher

### PR DESCRIPTION
**Pull request by npezza93**
Matches what is in `Reloader` and removes the listen dependency

### CODE REVIEW

**Comment by dhh** [comment]
Need some tests and also should pass in the file watcher from the railtie, not reference the Rails const inside the map directly.

**Comment by dhh** [comment]
Actually, never mind moving the Rails const. Fine to have it there. We're using other references like that.

**Comment by dhh** [comment]
@npezza93 Want to take a stab at adding some tests around this?

**Comment by mhenrixon** [comment]
Brilliant! This solved my issue with the `ruby/debug` gem!

**Pull request merged**
