### PR TITLE
Auto-reload importmap when it or javascript files change

### LINKED ISSUE #10: Add reloadable importmap.rb
Convert only-loaded-on-boot config/initializers/importmap.rb into reloaded-on-change config/importmap.rb. Just like routes.rb or i18n translations.

### PR DESCRIPTION
**Pull request by npezza93**
Fixes #10

Reload the importmap when it changes along with the js folder. The js folder needs to trigger a reload so we pick up any new files in pinned directories.

### CODE REVIEW

**Comment by dhh** [comment]
Thanks for taking this on! The `pin_all_from` is already dynamic, so we don't need the reloading based on that.

**Comment by dhh** [comment]
Also, I think we should actually just overwrite the definitions, rather than clear them. Otherwise we can't have gems add to the importmap without those additions disappearing.

**Comment by npezza93** [comment]
> The pin_all_from is already dynamic, so we don't need the reloading based on that.

Ahh yep. I forgot to turn off importmap caching locally. (Side note: Should we disable importmap caching by default in development even if `config.action_controller.perform_caching` is true?) 

> Also, I think we should actually just overwrite the definitions, rather than clear them. Otherwise we can't have gems add to the importmap without those additions disappearing.

:+1:

**Comment by npezza93** [comment]
> Also, I think we should actually just overwrite the definitions, rather than clear them. Otherwise we can't have gems add to the importmap without those additions disappearing.

Only drawback here is that you'll need to do a server restart if you want to clear any pins that have been deleted since the last restart. Dont think it'll be an issue though since it seems pretty uncommon that a deleted pin sticking around would causes any headache.

**Comment by dhh** [comment]
Yeah, I think that's fine. We can document that. It's only a dev concern anyway, and a minority one.

**Comment by npezza93** [comment]
Sweet, I think this is ready for another review then. The map clearing and listening for js changes have been removed.

**Comment by dhh** [comment]
Awesome. Will review this shortly. Delighted by how little code it turned out to be 👌

**Comment by dhh** [comment]
Would be nice with a test of this.

**Pull request merged**
